apiVersion: apps/v1
kind: Deployment
metadata:
  name: inception-server
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: inception-server
  template:
    metadata:
      labels:
        app: inception-server
    spec:
      containers:
      - name: inception-container
        image: wanziyu/inception:v1.0
       # image: gcr.io/tensorflow-serving/inception
        command:
        - ls serving
        #- cd serving
        #- /bin/sh
        #- -c
        #args:
        #- serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server
         # --port=9000 --model_name=inception --model_base_path=serving/inception-export
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: inception-service
  name: inception-service
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: inception-server
  type: LoadBalancer
