# permissions for end users to edit inferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inference-editor-role
rules:
- apiGroups:
  - melody.io
  resources:
  - inferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - melody.io
  resources:
  - inferences/status
  verbs:
  - get
