# permissions for end users to view inferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inference-viewer-role
rules:
- apiGroups:
  - melody.io
  resources:
  - inferences
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - melody.io
  resources:
  - inferences/status
  verbs:
  - get
