# permissions for end users to view schedulingdecisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schedulingdecision-viewer-role
rules:
- apiGroups:
  - melody.io
  resources:
  - schedulingdecisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - melody.io
  resources:
  - schedulingdecisions/status
  verbs:
  - get
