# permissions for end users to edit schedulingdecisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schedulingdecision-editor-role
rules:
- apiGroups:
  - melody.io
  resources:
  - schedulingdecisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - melody.io
  resources:
  - schedulingdecisions/status
  verbs:
  - get
