apiVersion: melody.io.melody.io/v1alpha1
kind: Inference
metadata:
  name: inference-sample
spec:
  domain: "time-series"
  replicas: 2
  servings:
    - name: model-predictor
      image: nginx:1.17.1
      modelVersion: model
      batchSize: 32


