apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: melody-mysql
  namespace: melody-system
  labels:
    app: melody
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
