// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: api.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SuggestionClient is the client API for Suggestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SuggestionClient interface {
	GetSuggestions(ctx context.Context, in *SchedulingRequest, opts ...grpc.CallOption) (*SchedulingResponse, error)
}

type suggestionClient struct {
	cc grpc.ClientConnInterface
}

func NewSuggestionClient(cc grpc.ClientConnInterface) SuggestionClient {
	return &suggestionClient{cc}
}

func (c *suggestionClient) GetSuggestions(ctx context.Context, in *SchedulingRequest, opts ...grpc.CallOption) (*SchedulingResponse, error) {
	out := new(SchedulingResponse)
	err := c.cc.Invoke(ctx, "/api.suggestion.Suggestion/GetSuggestions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuggestionServer is the server API for Suggestion service.
// All implementations must embed UnimplementedSuggestionServer
// for forward compatibility
type SuggestionServer interface {
	GetSuggestions(context.Context, *SchedulingRequest) (*SchedulingResponse, error)
	mustEmbedUnimplementedSuggestionServer()
}

// UnimplementedSuggestionServer must be embedded to have forward compatible implementations.
type UnimplementedSuggestionServer struct {
}

func (UnimplementedSuggestionServer) GetSuggestions(context.Context, *SchedulingRequest) (*SchedulingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuggestions not implemented")
}
func (UnimplementedSuggestionServer) mustEmbedUnimplementedSuggestionServer() {}

// UnsafeSuggestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SuggestionServer will
// result in compilation errors.
type UnsafeSuggestionServer interface {
	mustEmbedUnimplementedSuggestionServer()
}

func RegisterSuggestionServer(s grpc.ServiceRegistrar, srv SuggestionServer) {
	s.RegisterService(&Suggestion_ServiceDesc, srv)
}

func _Suggestion_GetSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestionServer).GetSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.suggestion.Suggestion/GetSuggestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestionServer).GetSuggestions(ctx, req.(*SchedulingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Suggestion_ServiceDesc is the grpc.ServiceDesc for Suggestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Suggestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.suggestion.Suggestion",
	HandlerType: (*SuggestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuggestions",
			Handler:    _Suggestion_GetSuggestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
