kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: melody-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - serviceaccounts
      - services
      - secrets
      - events
      - namespaces
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/status
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - '*'
  - apiGroups:
      - melody.io
    resources:
      - inferences
      - inferences/status
    verbs:
      - "*"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: melody-controller
  namespace: melody-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: melody-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: melody-controller
subjects:
  - kind: ServiceAccount
    name: melody-controller
    namespace: melody-system
